version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_biblioteca
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: BibliotecaDB1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
