version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: biblioteca-db
    environment:
      POSTGRES_DB: BibliotecaDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - biblioteca-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  biblioteca-data:
